### ISSUE TITLE
request.ip fails with new rack 2.2.0

### ISSUE THREAD

**Issue by martinlevesque** [kickstarter/rack-attack#474]
With the latest rack-attack gem and new rack 2.2.0 version, I am getting the following exception:

```
NoMethodError (undefined method `reject' for nil:NilClass):
  
config/initializers/rack_attack.rb:4:in `block in <main>'
```

My config/initializers/rack_attack.rb looks like

```
Rack::Attack.throttle("requests by ip", limit: 500, period: 60) do |request|
  Rails.logger.info("Request throttle ip = #{request.ip}")
  
  request.ip
end
```

And so whenever it hits request.ip it throws the exception.

**Comment by martinlevesque** [comment]
now working with rack 2.2.1... closing
